### ISSUE TITLE
NRF Panic when receiving a PATCH on a DELETEd /nnrf-nfm/v1/nf-instances/{nfInstanceId}

### ISSUE THREAD

**Issue by linouxis9** [free5gc/nrf#47]
Hi Free5GC Team!

I'm opening this issue to get to your attention that the NRF Panic when receiving a PATCH on a DELETEd /nnrf-nfm/v1/nf-instances/{nfInstanceId}.
Thanksfully, this does not crash the NRF as the panic is recovered by the Gin panic recoverer.

I'll open a PR :-)

PCAP:
[NRF - Panic on Patch.zip](https://github.com/user-attachments/files/18020933/NRF.-.Panic.on.Patch.zip)

Version:
Latest free5gc-compose (tag v3.4.4)
nrf v3.4.4 using Docker image docker.io/free5gc/nrf (4a21d51f646f)
mongo 6.0

Stacktrace:
```bash
2024-12-05T09:22:41.586556254Z [ERRO][NRF][GIN] panic: assignment to entry in nil map
goroutine 2542 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/free5gc/util/logger.NewGinWithLogrus.ginRecover.func2.1()
        /go/pkg/mod/github.com/free5gc/util@v1.0.6/logger/logger.go:284 +0x117
panic({0xc40460?, 0xeabda0?})
        /usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/evanphx/json-patch.(*partialDoc).set(0xca9840?, {0xc0005360a8?, 0xd15706?}, 0xc0005e6150)
        /go/pkg/mod/github.com/evanphx/json-patch@v0.5.2/patch.go:385 +0x36
github.com/evanphx/json-patch.Patch.replace({0xc000536000?, 0x4?, 0x8?}, 0xc6fec0?, 0xc00010e050?)
        /go/pkg/mod/github.com/evanphx/json-patch@v0.5.2/patch.go:561 +0x12c
github.com/evanphx/json-patch.Patch.ApplyIndent({0xc00010e000?, 0x1, 0x1}, {0xc000536000, 0x4, 0x8}, {0x0, 0x0})
        /go/pkg/mod/github.com/evanphx/json-patch@v0.5.2/patch.go:748 +0x30c
github.com/evanphx/json-patch.Patch.Apply(...)
        /go/pkg/mod/github.com/evanphx/json-patch@v0.5.2/patch.go:718
github.com/free5gc/util/mongoapi.RestfulAPIJSONPatch({0xd20329, 0x9}, 0xd23644?, {0xc00063e000, 0x3e, 0x200}, {0x0?, 0x0, 0x0})
        /go/pkg/mod/github.com/free5gc/util@v1.0.6/mongoapi/mongoapi.go:357 +0x231
github.com/free5gc/nrf/internal/sbi/processor.(*Processor).UpdateNFInstanceProcedure(0xc0002c95f0, {0xc0006b80da, 0x24}, {0xc00063e000, 0x3e, 0x200})
        /go/src/free5gc/NFs/nrf/internal/sbi/processor/nf_management.go:333 +0x10a
github.com/free5gc/nrf/internal/sbi/processor.(*Processor).HandleUpdateNFInstanceRequest(0x73ca6b39b640?, 0xc0007a8a20?, {0xc00063e000, 0x3e, 0x200}, {0xc0006b80da, 0x24})
        /go/src/free5gc/NFs/nrf/internal/sbi/processor/nf_management.go:51 +0xb0
github.com/free5gc/nrf/internal/sbi.(*Server).HTTPUpdateNFInstance(0xc0004bf1a0, 0xc000294300)
        /go/src/free5gc/NFs/nrf/internal/sbi/api_nfmanagement.go:196 +0x345
github.com/gin-gonic/gin.(*Context).Next(0xc000294300)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 +0x2b
github.com/free5gc/util/logger.NewGinWithLogrus.ginRecover.func2(0x9?)
        /go/pkg/mod/github.com/free5gc/util@v1.0.6/logger/logger.go:316 +0x57
github.com/gin-gonic/gin.(*Context).Next(0xc000294300)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 +0x2b
github.com/free5gc/util/logger.NewGinWithLogrus.ginToLogrus.func1(0xc000294300)
        /go/pkg/mod/github.com/free5gc/util@v1.0.6/logger/logger.go:251 +0x5f
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc000007d40, 0xc000294300)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 +0x65b
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc000007d40, {0xeb3418?, 0xc000582048}, 0xc0000d6800)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 +0x1dd
golang.org/x/net/http2.(*serverConn).runHandler(0xc00052c0d0?, 0xeb3e40?, 0xc00041c050?, 0xc00049a2e0?)
        /go/pkg/mod/golang.org/x/net@v0.23.0/http2/server.go:2369 +0xbb
created by golang.org/x/net/http2.(*serverConn).scheduleHandler in goroutine 2538
        /go/pkg/mod/golang.org/x/net@v0.23.0/http2/server.go:2304 +0x21d
```

Thanks!
Valentin

**Comment by andy89923** [comment]
Hi, 
Thanks for reporting issue and PR fix!

@williamlin0518 Please review this, thanks!
